name: home
timestamp: 1694883905
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1694881473
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  sample:
    sample-1: 'Gantry 5'
    sample-2: 'Getting Started'
    sample-3: 'Key Features'
  messages:
    system-messages-3047: 'System Messages'
    system-messages-9631: 'System Messages'
  position:
    position-footer: Footer
  copyright:
    copyright-1485: Copyright
  social:
    social-7724: Social
  branding:
    branding-8078: Branding
  mobile-menu:
    mobile-menu-2427: 'Mobile Menu'
  logo:
    logo-3178: Logo
  menu:
    menu-3315: Menu
inherit:
  default:
    header: header
    navigation: navigation
    system-messages-9631: system-messages-1801
    logo-3178: logo-1669
    menu-3315: menu-4069
