version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1694881473
layout:
  /header/:
    -
      - 'logo-3161 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-1157
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-8460
    -
      - system-content-6399
  /footer/:
    -
      - position-footer
    -
      - 'copyright-8880 40'
      - 'spacer-3137 30'
      - 'branding-7625 30'
  offcanvas:
    -
      - mobile-menu-1641
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
