name: _body_only
timestamp: 1694881478
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1694881473
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-5559: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-4320: Menu
  messages:
    system-messages-5124: 'System Messages'
  content:
    system-content-7514: 'Page Content'
  copyright:
    copyright-4093: Copyright
  spacer:
    spacer-4910: Spacer
  branding:
    branding-1701: Branding
  mobile-menu:
    mobile-menu-8348: Mobile-menu
inherit: {  }
