version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1694881473
layout:
  /header/: {  }
  /navigation/:
    -
      - system-messages-6072
  /main/:
    -
      - system-content-2520
  /footer/: {  }
  offcanvas: {  }
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
