name: _offline
timestamp: 1694881478
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1694881473
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-1849: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-3375: Menu
  messages:
    system-messages-6592: 'System Messages'
  content:
    system-content-4830: 'Page Content'
  copyright:
    copyright-2616: Copyright
  spacer:
    spacer-5781: Spacer
  branding:
    branding-1046: Branding
  mobile-menu:
    mobile-menu-6577: Mobile-menu
inherit: {  }
