version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1694881473
layout:
  /header/:
    -
      - 'logo-1849 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-3375
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-6592
    -
      - system-content-4830
  /footer/:
    -
      - position-footer
    -
      - 'copyright-2616 40'
      - 'spacer-5781 30'
      - 'branding-1046 30'
  offcanvas:
    -
      - mobile-menu-6577
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
